const state={player:1000,enemy:1200,energy:72,combo:0,over:false,sound:true};
const $=id=>document.getElementById(id);
const els={player:$('player'),enemy:$('enemy'),impact:$('impact'),message:$('message'),combo:$('combo'),energy:$('energy'),energyText:$('energyText'),playerHealth:$('playerHealth'),enemyHealth:$('enemyHealth'),playerHpText:$('playerHpText'),enemyHpText:$('enemyHpText'),modal:$('modal')};

function announce(text){els.message.textContent=text;els.message.classList.remove('show');void els.message.offsetWidth;els.message.classList.add('show')}
function update(){els.playerHealth.style.width=`${state.player/10}%`;els.enemyHealth.style.width=`${state.enemy/12}%`;els.energy.style.width=`${state.energy}%`;els.energyText.textContent=`${state.energy}%`;els.playerHpText.textContent=`${state.player} / 1000`;els.enemyHpText.textContent=`${state.enemy} / 1200`;els.combo.querySelector('strong').textContent=state.combo;els.combo.classList.toggle('show',state.combo>0);document.querySelector('[data-skill="domain"]').classList.toggle('locked',state.energy<100)}
function effect(){els.impact.classList.remove('burst');void els.impact.offsetWidth;els.impact.classList.add('burst');els.enemy.classList.remove('hit');void els.enemy.offsetWidth;els.enemy.classList.add('hit')}
function attack(type){if(state.over)return;const moves={rush:{cost:12,damage:95,name:'逕庭拳！'},flash:{cost:35,damage:210,name:'黒 閃！'},domain:{cost:100,damage:520,name:'領域展開——伏魔御厨子'}};const move=moves[type];if(state.energy<move.cost){announce('呪力不足');return}state.energy-=move.cost;state.enemy=Math.max(0,state.enemy-move.damage-Math.floor(Math.random()*30));state.combo++;effect();announce(move.name);update();if(state.enemy<=0)return end(true);setTimeout(enemyAttack,650)}
function enemyAttack(){if(state.over||Math.random()<.28)return;state.player=Math.max(0,state.player-(55+Math.floor(Math.random()*70)));state.combo=0;els.player.classList.remove('hit');void els.player.offsetWidth;els.player.classList.add('hit');announce('呪炎襲来');update();if(state.player<=0)end(false)}
function dodge(){if(state.over)return;els.player.classList.remove('dodge');void els.player.offsetWidth;els.player.classList.add('dodge');state.energy=Math.min(100,state.energy+8);announce('回避成功 +8%');update()}
function movePlayer(direction){if(state.over)return;const arena=$('arena').getBoundingClientRect();const fighter=els.player.getBoundingClientRect();const current=parseFloat(getComputedStyle(els.player).left);const next=current+(direction==='left'?-18:18);els.player.style.left=`${Math.max(8,Math.min(arena.width-fighter.width-8,next))}px`}
function end(win){state.over=true;setTimeout(()=>{els.modal.classList.add('show');els.modal.setAttribute('aria-hidden','false');$('resultTitle').textContent=win?'祓除完了':'戦闘不能';$('resultText').textContent=win?`${state.combo} COMBOで特級呪霊を祓いました`:'呪力の流れを見極め、もう一度挑め。'},500)}
document.querySelectorAll('.skill').forEach(btn=>btn.addEventListener('click',()=>attack(btn.dataset.skill)));
document.addEventListener('keydown',e=>{if(e.repeat)return;const key=e.key.toLowerCase();if(key==='q')attack('rush');if(key==='w')attack('flash');if(key==='e')attack('domain');if(e.code==='Space'){e.preventDefault();dodge()}if(key==='a'||key==='d')movePlayer(key==='a'?'left':'right')});
document.querySelectorAll('[data-move]').forEach(button=>{let timer;const stop=()=>{clearInterval(timer);timer=undefined};button.addEventListener('pointerdown',event=>{event.preventDefault();button.setPointerCapture(event.pointerId);movePlayer(button.dataset.move);timer=setInterval(()=>movePlayer(button.dataset.move),70)});button.addEventListener('pointerup',stop);button.addEventListener('pointercancel',stop);button.addEventListener('lostpointercapture',stop)});
$('dodgeButton').addEventListener('pointerdown',event=>{event.preventDefault();dodge()});
$('restart').addEventListener('click',()=>location.reload());$('soundBtn').addEventListener('click',e=>{state.sound=!state.sound;e.currentTarget.querySelector('b').textContent=state.sound?'ON':'OFF'});
setInterval(()=>{if(!state.over&&state.energy<100){state.energy=Math.min(100,state.energy+1);update()}},900);update();setTimeout(()=>announce('戦闘開始'),400);
